### ISSUE TITLE
Helix support

### ISSUE THREAD

**Issue by rome-user** [cjohansen/portfolio#1]
This library looks like a promising alternative to devcards. I am wondering if a library like Helix is supported? Helix renders to pure React components. Is there a way to provide a pure React component to `defscene`? If so, then that is great news. Otherwise, what would be some steps to take to attain Helix support? I am willing to send PRs to assist in this effort.

**Comment by cjohansen** [comment]
There isn't yet, but that would be a very welcome addition!

There is a small layer that takes care of the rendering, take a look at the reagent implementation for a sample:

https://github.com/cjohansen/portfolio/blob/main/src/portfolio/reagent.cljs

And then there's a thin macro that exposes it with the same API as the other adapters - this one can just be copy-pasted and updated with the right namespaces:

https://github.com/cjohansen/portfolio/blob/main/src/portfolio/reagent.clj

It would be great if you wanted to take a stab at it. If you're using Emacs, then just jack-in-cljs and you'll have the demo up and running, where you can add a Helix component to test it. If you're not in Emacs I can add some REPL instructions to the Readme.

Feel free to ask for help, you'll find me on the Clojurians slack as well 😊
