### ISSUE TITLE
Help with Portfonio + Mantine CSS

### ISSUE THREAD

**Issue by rafaeldelboni** [cjohansen/portfolio#21]
Hey, first of all, thanks for this tool it will help a lot and is a missing (updated) piece in the cljs ecosystem.

I'm trying to set it up to work with [mantine](https://mantine.dev) component library, but It uses a wrapper component called [MantineProvider](https://mantine.dev/theming/mantine-provider/) to handle themes and CSS stuff.

And even wrapping my component with it on the `defscene`, it looks like is not able to do all the CSS changes it does in a normal app.
```clj
(defscene mantine-button
  ($ MantineProvider {:theme c/theme}
     ($ c/button {:text "My Button"
                  :on-click #(js/console.log "clicked!")
                  :color "blue"})))
```
 Normal app:
<img width="852" alt="image" src="https://github.com/cjohansen/portfolio/assets/1683898/d79a5c48-0303-43ce-97c5-92d822ec3a6e">

Portfolio:
<img width="1028" alt="image" src="https://github.com/cjohansen/portfolio/assets/1683898/474f3d99-c877-4c09-9137-c3ae175ec6d8">

Other than that all components, apart from the visuals are working as they should.

I've made a sample repo to help you to see this happening:
https://github.com/rafaeldelboni/helix-jsdom-portfolio-mantine

**My question is, is there a way to declare a root component to defscene run all components inside of it? Because this bug can happen in a normal app, if you add mantine css, but do not use the `MantineProvider`, so looks like the `MantineProvider` in the `defscene` is conflicting with some wrap portfolio may be doing.**

**Comment by vloth** [comment]
I've looked a bit into this and made it work by adding a custom canvas with forced light theme
<img width="735" alt="image" src="https://github.com/cjohansen/portfolio/assets/49727703/0149e7f4-cf0c-45ed-9897-a5892650a865">
The component `MantineProvider` seems to be adding the data theme property to the html element as a side effect, which is important to apply the correct CSS variables.  
It might be easier to understand by looking at the changeset: https://github.com/vloth/helix-jsdom-portfolio-mantine/commit/e403538fa06b0ab9028d93e437b38f72d1bc94a4
I'm not entirely sure how the side effects are handled by portfolio, but the css classes seems to be applied correctly. I can see the html has the class `light-mode`.  
I hope that helps troubleshooting ?

**Comment by rafaeldelboni** [comment]
Thanks @vloth, that fixed the problem :)
