### ISSUE TITLE
wrapper, decorator support

### ISSUE THREAD

**Issue by taehee-sp** [cjohansen/portfolio#28]
## problem
we have a lot of scenes, we want to add new context or provider to existing scenes

## feature request
we want to configure global decorator(wrapper) to our scenes.

storybook's decorator
https://storybook.js.org/docs/writing-stories/decorators

react cosmos's decortator
https://reactcosmos.org/docs/fixtures/decorators

If you don't mind, I'd like to do it myself to all adapter and make a pull request.

**Comment by cjohansen** [comment]
I can see the appeal of a global decorator that adds markup around components. I'm not so sure about "context" - it's not clear to me what that is, and I really don't want a lot of state management in Portfolio, as it's designed primarily to display resulting components based on static input data.

Do you have a suggested API for this?

**Comment by taehee-sp** [comment]
We don't need to manage state in portfolio. The only thing I want to do is wrapping scene component with Context Provider (like toast provider, modal provider, router provider and so on) [react context for dependency injection, not for state management](https://blog.testdouble.com/posts/2021-03-19-react-context-for-dependency-injection-not-state/).

Here is my initial thought.

```clojure
;; reagent
(defn wrapper [{:keys [children]}]
              [theme-provider {}
               children
               [toast-component]])

(ui/start!
 {:config {:decorator {:type :reagent-18 :wrapper wrapper}})

;; uix
(defui wrapper [{:keys [children]}]
             ($ theme-provider {}
                children
                ($ toast-component {})))

(ui/start!
 {:config {:decorator {:type :uix :wrapper wrapper}})
```

**Comment by cjohansen** [comment]
I see. That looks good to me. A PR with this would be cool 😊
