### ISSUE TITLE
Html data attribute does not update on theme switch

### ISSUE THREAD

**Issue by sprocketc** [cjohansen/portfolio#32]
Thank you for this cool project!
I run into a theme issue using the following config 
```clojure
{:config
  {:background/default-option-id :dark-mode
   :background/options [{:id :light-mode
                         :title "Light mode"
                         :value {:background/background-color "#fff"
                                 :background/document-data {:theme "light"}}}
                        {:id :dark-mode
                         :title "Dark mode"
                         :value {:background/background-color "#111"
                                 :background/document-data {:theme "dark"}}}]}}
```
The initial value of the `data-theme` attribute is properly set to `dark`. When I am trying to switch to light mode, its value remains `dark`. Clearing my local storage didn't help. Note that only `background/document-data` seems to have this problem. `background/document-class` works as intended.

**Comment by cjohansen** [comment]
Thanks for reporting! I just fixed this and released 2024.09.25.
