### ISSUE TITLE
Why are the overflows `scroll` rather than `auto`?

### ISSUE THREAD

**Issue by elken** [cjohansen/portfolio#8]
Love portfolio! Working on migrating devcards over to it at work atm and it's an absolute joy in comparison.

One thing I have noticed is the various containers are marked as `overflow: scroll` rather than `overflow: auto` which leads to a collection of scrollbar arrows at the bottom, is there a specific reason for this?
![image](https://user-images.githubusercontent.com/2872862/233937024-43fd602b-b3dc-403f-8d18-29db094b8e3f.png)

**Comment by cjohansen** [comment]
Thanks, very glad to hear you're enjoying it :)

Well, this doesn't look so great. The idea with `overflow: scroll` is to allow big scenes to scroll when necessary. But there should really only be one container with this setting. I've been a little back and forth on how to implement the grid layout, so I'll have a look to see if I can clean it up a little.

**Comment by elken** [comment]
Just saw the ninja edit as I was writing my comment :P 

I think so, it'll only add in the scrollbar when there's content to scroll

**Comment by cjohansen** [comment]
If you're able to use Portfolio from git, could you try the current head? I'll use it a little myself before I cut a release, just to make sure I didn't break anything.

**Comment by elken** [comment]
> If you're able to use Portfolio from git, could you try the current head? I'll use it a little myself before I cut a release, just to make sure I didn't break anything.

Will try it out now

**Comment by elken** [comment]
Yes that seems much nicer! Free of scrollbars and they show up much rarer now.

**Comment by cjohansen** [comment]
Cool 👍
